name: Mac

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
       include:
         - os: macos-latest
           upload: 1
    runs-on: ${{ matrix.os }}
    env:
      UPLOAD: ${{ matrix.upload }}
    steps:
    - uses: actions/checkout@v2
    - name: Release Build
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      run: |
        chmod +x ports/ci/mac/build.sh
        ./ports/ci/mac/build.sh
    - name: Daily Build
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      env:
        DAILY_BUILD: 1
      run: |
        chmod +x ports/ci/mac/build.sh
        ./ports/ci/mac/build.sh
#    - name: VirusTotal Scan
#      uses: crazy-max/ghaction-virustotal@v4
#      if: ${{ matrix.upload && secrets.VT_API_KEY != '' }}
#      with:
#        vt_api_key: ${{ secrets.VT_API_KEY }}
#        files: |
#          webcamoid-packages/mac/*
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      if: ${{ matrix.upload }}
      with:
        name: mac-packages-${{ github.sha }}
        path: webcamoid-packages/mac/*
        retention-days: 90
